### ISSUE TITLE
Needs LICENSE

### ISSUE THREAD

**Issue by stianjensen** [dmpro2014/dmpro2014.github.io#1]

**Comment by cristeahub** [comment]
Is this the licence for the web page or for the actual project?

**Comment by stianjensen** [comment]
That would be for the website in this case.
We may also choose to just retain the copyright, but I'd say we can slam a pretty permissive license on this, so others can use the source for their own static sites.

**Comment by cristeahub** [comment]
I'ld say MIT, what do you think?

**Comment by stianjensen** [comment]
:+1:
